### ISSUE TITLE
Autoselect profile with matching name/email

### ISSUE THREAD

**Issue by nikolay-borzov** [onlyutkarsh/git-config-user-profiles#31]
# Summary of the new feature/enhancement

It seems natural to me that the selected profile should be determined by examining the repository `config` name/email so that the user can see under what user he's working. Currently, if a user opens a repo he sees the last selected profile and has to select the profile matching the current repository name/email pair

# Proposed technical implementation details (optional)

When a repo is opened and there is name/email pair specific in repository `config` pre-select profile with the same name/email (if presented) w/o showing a warning icon.
When there is no name/email in the repository `config` try to get global name/email

**Comment by onlyutkarsh** [comment]
@nikolay-borzov - thank you for suggestion. I like this idea. Let me experiment with it and come back. As of now I am bit busy with work, but hopefully able to add this over the Christmas break. Thanks.

**Comment by Shaokun-X** [comment]
Hi please have a look at https://github.com/onlyutkarsh/git-config-user-profiles/pull/45, I am new to VSC extension, so feel free to leave a comment or just change it!

**Comment by onlyutkarsh** [comment]
Thanks to #45, This is now fixed in the latest version (v1.1.0)
