### ISSUE TITLE
Unable to configure profiles for multi root workspace

### ISSUE THREAD

**Issue by Naveenchandar** [onlyutkarsh/git-config-user-profiles#34]
![image](https://user-images.githubusercontent.com/37447901/102006537-e9d5b000-3d47-11eb-84e3-f0f68d6033ed.png)

I'm trying to configure work account and personal account in my workspace. But its not supported.

**Comment by onlyutkarsh** [comment]
@Naveenchandar thanks for reporting this. I do not have plans to work on this anytime soon unfortunately.

**Comment by onlyutkarsh** [comment]
Sorry, it took so long, the extension supports multi-root workspace now from v1.2.0

![image](https://user-images.githubusercontent.com/2685029/190898345-0a8b55c5-60a7-4394-bc22-fc9110d4319a.png)
