### ISSUE TITLE
Error: This does not seem to be a valid git repository

### ISSUE THREAD

**Issue by ThinkDualBrain** [onlyutkarsh/git-config-user-profiles#6]
**Describe the bug**
After creating a profile, clicking the taskbar shows an error "This does not seem to be a valid git repository", even if the workspace is a git repo.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open any folder with a .git repo initialized
2. Click on status bar and create a profile (if one doesn't exist, otherwise next step)
3. Click on status bar to get error notification

**Expected behaviour**
Show [the prompt](https://github.com/onlyutkarsh/git-config-user-profiles/raw/master/images/marketplace/statusbar-picker.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/3466696/83689638-5d3e7e00-a5bd-11ea-827b-cae19447bb6b.png)

**Console**
[INFO - 3:58:45 PM] Activating extension
[INFO - 3:58:45 PM] Registering for config change event
[INFO - 3:58:45 PM] Initializing status bar
[INFO - 3:58:45 PM] Initializing status bar complete.
[INFO - 3:58:45 PM] Initializing commands
[INFO - 3:58:45 PM] Initializing commands complete.
[INFO - 3:58:45 PM] Getting user profiles. Triggerred from status bar = false
[INFO - 3:59:30 PM] Getting user profiles. Triggerred from status bar = false
[INFO - 5:06:10 PM] Getting user profiles. Triggerred from status bar = true
[INFO - 5:10:44 PM] Getting user profiles. Triggerred from status bar = true

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode: 1.45.1

**Additional context**
Brand new install.

**Comment by onlyutkarsh** [comment]
@ThinkDualBrain thanks for letting me know - that is strange. I will try to repro this over the weekend. Although I might need to increase the logging to the output window. Seeing what is currently written there, it is not that helpful.

**Comment by ThinkDualBrain** [comment]
Understood. Let me know if you need me to test anything!

**Comment by onlyutkarsh** [comment]
@ThinkDualBrain can you please repro this for me and verify if your folder has `.git` sub-folder? If yes, can you please let me know the tree structure of the folder are you on? maybe something like this so that I can create and try

```
/my-project
/my-project/.git
/my-project/src
/my-project/src/main.ts
/my-project/readme.md
/my-project/package.json
```

**Comment by ThinkDualBrain** [comment]
It does. This is the actual structure of one of my project (name changed to "my-project"), but otherwise this hierarchy:

`my-project/.git
my-project/app
my-project/configs
my-project/dll
my-project/internals
my-project/resources
my-project/test
my-project/.dockerignore
my-project/.editorconfig
my-project/.eslintignore
my-project/.eslintrc.js
my-project/.gitattributes
my-project/.gitignore
my-project/azure-pipelines.yml
my-project/babel.config.js
my-project/CHANGELOG.md
my-project/LICENSE
my-project/package.json
my-project/README.md
my-project/tsconfig.json
my-project/yarn.lock`

**Comment by ThinkDualBrain** [comment]
Setup a new blank project to make sure it wasn't just something with my existing repo. You can clone it here: https://github.com/ThinkDualBrain/git-config-user-profiles-debugging

Same error though.

**Comment by onlyutkarsh** [comment]
@ThinkDualBrain thanks for the sample repo - I cloned your repo but I could not repro the issue. I also opened an empty folder and then initialised as git repo, the extension worked without issues. I will have to increase the logging and provide you a beta version to capture the logs.

**Comment by onlyutkarsh** [comment]
Can you try [**this**](https://github.com/onlyutkarsh/git-config-user-profiles/suites/764175732/artifacts/7950727) VSIX file? Use the following steps to install the extension, see if you can repro the issue and paste the text from output window.

- Uninstall install extension
- Unzip the downloaded file and you should have beta version of VSIX
- Then in VS Code from `Extensions` pane, use `Install from VSIX` and select the VSIX file downloaded.
![image](https://user-images.githubusercontent.com/2685029/83950712-be1bbf80-a824-11ea-9942-129e778eb5c4.png)

Also, can you please run following command from the root folder and let me know the output? You should get `true` or `false`

```bash
git rev-parse --is-inside-work-tree
```

**Comment by onlyutkarsh** [comment]
Since I have not received any response, I assume you no longer have this issue. Please reopen, if you still get this issue.

**Comment by ThinkDualBrain** [comment]
Sorry, was on some tight deadlines and couldn't revisit until now. Still no luck, but the error console is providing more details:

`[INFO - 9:53:27 AM] Activating extension
[INFO - 9:53:27 AM] Registering for config change event
[INFO - 9:53:27 AM] Initializing status bar
[INFO - 9:53:27 AM] Initializing status bar complete.
[INFO - 9:53:27 AM] Initializing commands
[INFO - 9:53:27 AM] Initializing commands complete.
[INFO - 9:53:27 AM] Getting user profiles. Triggerred from status bar = false
[ERROR - 9:53:27 AM] Unable to detect if C:\projects\test-repo is git repository: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[ERROR - 9:53:27 AM] Unable to detect if C:\projects\test-repo is git repository: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[INFO - 9:53:45 AM] Getting user profiles. Triggerred from status bar = true
[ERROR - 9:53:45 AM] Unable to detect if C:\projects\test-repo is git repository: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[ERROR - 9:53:45 AM] Unable to detect if C:\projects\test-repo is git repository: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
`

And the output of `git rev-parse --is-inside-work-tree` is "true"

**Comment by onlyutkarsh** [comment]
No worries - Looks like you are hitting issue similar to what is mentioned [here](https://stackoverflow.com/questions/42545885/vs-code-error-spawn-git-enoent). Did you say you ran `git rev-parse --is-inside-work-tree` this from VSCode terminal? Is VSCode able to commit/pull without any issues?

**Comment by ThinkDualBrain** [comment]
Correct, both that command and the one below were run from within the VSCode terminal. I also ran `git log` and got this (truncated) output:

`$ git log
commit f0a0b0fa3afc7ab5ad8ff80864fdb0a4be28a546 (HEAD -> hotfix/listings-filters)
Author: Brian J. Hall <brian@thinkdualbrain.com>
Date:   Mon Jun 22 13:14:14 2020 -0400

    Fixing warnings

commit e2b5841a6dddc2d3215124eda173861cad64a3fc
Author: Brian J. Hall <brian@thinkdualbrain.com>
Date:   Mon Jun 22 13:00:02 2020 -0400

    Fixed placeholder image TYPE on details header`

This was just some work I was doing today, but git commands are running successfully in the VSCode terminal.

If it's useful, I'm on Windows, so the terminal being run is the Bash shell that comes with the git binaries found here: https://gitforwindows.org/

**Comment by onlyutkarsh** [comment]
Thanks for that. really strange that you have `git` working but extension fails. As you might see in the source code, I use `simple-git` npm package to check whether the current workspace is a git repo. Since you have issue only with the extension and not with `git` command, I might need to spend more time to troubleshoot and increase the logging.

**Comment by s6fcda** [comment]
@ThinkDualBrain 
Is there a chance that the folder root you added into VSCode is somewhere outside your repo (e.g. one level above)?

I went into the same issue just now. Even if my focus is on a file that is inside the repo, I got the same error, because my folder root was one level above the repo. Once I added the repo folder as the root, I can now switch the profile.

Sorry if this is unrelated.

**Comment by onlyutkarsh** [comment]
Please give this try using the latest version.

**Comment by vonschappler** [comment]
Hello there - I'd like to know if there is a workaround for the error "This does not seem to be a valid git repository" when trying to configure, create and switch profiles within a repo.

I am using the version below
![image](https://github.com/onlyutkarsh/git-config-user-profiles/assets/37213588/a0261437-7cf6-47ed-a7dc-449ea9340770)

and this is my current directory structure:

![image](https://github.com/onlyutkarsh/git-config-user-profiles/assets/37213588/b93dfe35-fa52-4d2f-86bb-11e9af376514)

Best regards!
