### ISSUE TITLE
What about deleting git user?

### ISSUE THREAD

**Issue by mepsd** [onlyutkarsh/git-config-user-profiles#71]
can we give a option to end users to delete user as well?

**Comment by onlyutkarsh** [comment]
fixed in [1.3.4](https://github.com/onlyutkarsh/git-config-user-profiles/releases/tag/v1.3.4)

**Comment by onlyutkarsh** [comment]
fixed in [1.3.4](https://github.com/onlyutkarsh/git-config-user-profiles/releases/tag/v1.3.4)
