### ISSUE TITLE
publish to open-vsx.org.

### ISSUE THREAD

**Issue by Kivylius** [onlyutkarsh/git-config-user-profiles#74]
# Summary of the new feature/enhancement

publish to the open source openvsx vendor neutral registry

about: https://github.com/eclipse/openvsx
publish docs:https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by onlyutkarsh** [comment]
This should work going forward - https://open-vsx.org/extension/onlyutkarsh/git-config-user-profiles
